openapi: "3.0.0"
info:
  version: 1.0.0
  title: Announcement MicroService
  description: A small serverless application (MicroService) which exposes JSON formatted REST APIs which allow for storing and retrieving announcements.

paths:
  /v1/announcements:
    get:
      summary: Returns list of all announcements
      responses:
        200:
          description: Successful data reading from the table
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Announcement"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ReadFunction.Arn}/invocations
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
        responses:
          default:
            statusCode: "200"
      security:
        - NONE: []

    post:
      summary: Allows to create a new announcement
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Announcement"
      responses:
        201:
          description: Created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Announcement"
        400:
          description: No mandatory body parameters
          content:
            application/json:
              schema:
                type: string
                example: Some mandatory body parameters are missing (title, date)!
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
                example: Unauthorized
        403:
          description: No access
          content:
            application/json:
              schema:
                type: string
                example: User is not authorized to access this resource with an explicit deny

      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WriteFunction.Arn}/invocations
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
        responses:
          default:
            statusCode: "201"
        default:
          description: An Error
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    Announcement:
      type: object
      required:
        - title
        - date
      properties:
        title:
          type: string
          example: "Free english classes"
        description:
          type: string
          example: "Free conversational English classes will start at Language Room, Central Library."
        date:
          type: string
          format: date-time
          example: "2022-02-12 15:00"
