# This workflow will install Python dependencies, checks black, isort, flake8

name: Code quality checks

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install -r requirements.txt
        
  black:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: python -m pip install black
    - name: Run formatting check
      run: black . --check
      
  isort:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: python -m pip install isort
    - name: Run sorting check
      run: isort . --check --profile=black
      
  flake8:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: python -m pip install flake8
    - name: Run linter
      run: flake8 .
